/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.stokestonkes.interfaces;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author marco.silva
 */
public class Home_Form extends javax.swing.JFrame {

    /**
     * Creates new form Home_Form
     */
    public Home_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        Desktop = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuarioLogado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDataAtual = new javax.swing.JLabel();
        mnsPrincipal = new javax.swing.JMenuBar();
        mnsArquivo = new javax.swing.JMenu();
        mnsRotinas = new javax.swing.JMenu();
        mnsCadastro = new javax.swing.JMenu();
        mnsCadastroCliente = new javax.swing.JMenuItem();
        mnsCadastroUsuario = new javax.swing.JMenuItem();
        mnsRelatorio = new javax.swing.JMenu();
        mnsAjuda = new javax.swing.JMenu();
        mnsAjudaSobre = new javax.swing.JMenuItem();
        mnsOpcoes = new javax.swing.JMenu();
        mnsOpcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StokeStonkes - HOME");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 435, Short.MAX_VALUE)
        );

        Desktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/stokestonkes/icones/Icone_Principal.png"))); // NOI18N

        jLabel2.setText("Usuário:");

        lblUsuarioLogado.setText("user");

        jLabel4.setText("Data:");

        lblDataAtual.setText("dataatual");

        mnsPrincipal.setPreferredSize(new java.awt.Dimension(64, 30));

        mnsArquivo.setText("Arquivo");
        mnsPrincipal.add(mnsArquivo);

        mnsRotinas.setText("Rotinas");

        mnsCadastro.setText("Cadastro");

        mnsCadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mnsCadastroCliente.setText("Cliente");
        mnsCadastro.add(mnsCadastroCliente);

        mnsCadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnsCadastroUsuario.setText("Usuários");
        mnsCadastroUsuario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mnsCadastroUsuarioStateChanged(evt);
            }
        });
        mnsCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsCadastroUsuarioActionPerformed(evt);
            }
        });
        mnsCadastro.add(mnsCadastroUsuario);

        mnsRotinas.add(mnsCadastro);

        mnsPrincipal.add(mnsRotinas);

        mnsRelatorio.setText("Relátorios");
        mnsRelatorio.setFocusable(false);
        mnsPrincipal.add(mnsRelatorio);

        mnsAjuda.setText("Ajuda");

        mnsAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        mnsAjudaSobre.setText("Sobre");
        mnsAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsAjudaSobreActionPerformed(evt);
            }
        });
        mnsAjuda.add(mnsAjudaSobre);

        mnsPrincipal.add(mnsAjuda);

        mnsOpcoes.setText("Opções");
        mnsOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsOpcoesActionPerformed(evt);
            }
        });

        mnsOpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mnsOpcoesSair.setText("Sair");
        mnsOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnsOpcoesSairActionPerformed(evt);
            }
        });
        mnsOpcoes.add(mnsOpcoesSair);

        mnsPrincipal.add(mnsOpcoes);

        setJMenuBar(mnsPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Desktop)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioLogado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 524, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDataAtual)
                .addGap(46, 46, 46))
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblUsuarioLogado)
                            .addComponent(jLabel4)
                            .addComponent(lblDataAtual))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnsOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsOpcoesSairActionPerformed
        // Fechando o sistema
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair", "Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mnsOpcoesSairActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas abaixo substituem a label data lblDataAtual ao inicializar o form
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblDataAtual.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void mnsOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsOpcoesActionPerformed
        //
    }//GEN-LAST:event_mnsOpcoesActionPerformed

    private void mnsAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsAjudaSobreActionPerformed
        // Chamando a tela sobre
        Home_Ajuda_Sobre_Form sobre = new Home_Ajuda_Sobre_Form();
        sobre.setVisible(true);
        //lembre de colocar no DefaultCloseOperation do form lá como dispose
    }//GEN-LAST:event_mnsAjudaSobreActionPerformed

    private void mnsCadastroUsuarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mnsCadastroUsuarioStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_mnsCadastroUsuarioStateChanged

    private void mnsCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnsCadastroUsuarioActionPerformed
        // Chamando o forms GUI SWING > form jinternalFrame, chamando o Home_Rotinas_usuarios dentro do desktop
        Home_Rotinas_Usuarios usuario = new Home_Rotinas_Usuarios();
        usuario.setVisible(true);
        desktop.add(usuario);
    }//GEN-LAST:event_mnsCadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Desktop;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDataAtual;
    private javax.swing.JLabel lblUsuarioLogado;
    private javax.swing.JMenu mnsAjuda;
    private javax.swing.JMenuItem mnsAjudaSobre;
    private javax.swing.JMenu mnsArquivo;
    private javax.swing.JMenu mnsCadastro;
    private javax.swing.JMenuItem mnsCadastroCliente;
    public static javax.swing.JMenuItem mnsCadastroUsuario;
    private javax.swing.JMenu mnsOpcoes;
    private javax.swing.JMenuItem mnsOpcoesSair;
    private javax.swing.JMenuBar mnsPrincipal;
    public static javax.swing.JMenu mnsRelatorio;
    private javax.swing.JMenu mnsRotinas;
    // End of variables declaration//GEN-END:variables
}
